module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        'index', 
      //'intro/environment', 
      //'intro/cli', 
      //'intro/cdn', 
      //'intro/vscode-extension', 
      //'intro/next'
      ],
    },
    {
      type: 'category',
      label: 'Module/Library',
      collapsed: false,
      items: [
        'intro/cdn',
        //'updating/6-0',
        //'updating/5-0',
        //'updating/4-0'
      ]
    },
    {
      type: 'category',
      label: 'Debugging',
      collapsed: false,
      items: [
        'intro/cdn',
        //'updating/6-0',
        //'updating/5-0',
        //'updating/4-0'
      ]
    },
    {
      type: 'category',
      label: 'Framework',
      collapsed: true,
      items: [
        'intro/cdn',
        //'updating/6-0',
        //'updating/5-0',
        //'updating/4-0'
      ]
    },
    {
      type: 'category',
      label: 'Database',
      collapsed: true,
      items: [
        'intro/cdn',
        //'updating/6-0',
        //'updating/5-0',
        //'updating/4-0'
      ]
    },
    {
      type: 'category',
      label: 'Dev-Ops',
      collapsed: true,
      items: [
        'intro/cdn',
        //'updating/6-0',
        //'updating/5-0',
        //'updating/4-0'
      ]
    },
    {
      type: 'category',
      label: 'Certificates',
      collapsed: true,
      items: [
        'intro/cdn',,
        {
          type: 'category',
          label: '정보처리기사',
          items: [
            'intro/cdn',

          ],
        },
        'intro/cdn',,

      ],
    },
    // {
    //   type: 'category',
    //   label: 'Uncategorized',
    //   collapsed: true,
    //   items: [
    //     'intro/cdn',,
    //     //'updating/6-0',
    //     //'updating/5-0',
    //     //'updating/4-0'
    //   ]
    // },

  ],
  uncategorized: [
    {
      type: 'category',
      label: 'Uncategorized',
      collapsed: false,
      items: ['uncategorized/자바스크립트 Promise & Async Await 004eed99c774402bafad8d1d4c67276a'],
    },
    {
      type: 'category',
      label: 'Uncategorized2',
      collapsed: true,
      items: ['uncategorized/자바 스크립트 기본 - Hello fa75a747a96e43588630088939fb6324'],
    },
  ],

  // api: [
  //   {
  //     type: 'category',
  //     label: 'Getting Started',
  //     collapsed: false,
  //     // items: ['components'],
  //   },
  // ],

  // cli: [
  //   {
  //     type: 'category',
  //     label: 'CLI Documentation',
  //     collapsed: false,
  //     // items: [
  //     //   'cli',
  //     //   'cli/configuration',
  //     //   'cli/livereload',
  //     //   'cli/using-a-proxy',
  //     //   {
  //     //     type: 'link',
  //     //     label: 'Changelog',
  //     //     href: 'https://github.com/ionic-team/ionic-cli/blob/develop/packages/@ionic/cli/CHANGELOG.md',
  //     //   },
  //     // ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Command Reference',
  //     collapsed: false,
  //     items: [
  //       {
  //         type: 'autogenerated',
  //         dirName: 'cli/commands', // Generate section automatically based on files
  //       },
  //     ],
  //   },
  // ],

};
